### ISSUE TITLE
 cmisaction for  update property

### ISSUE THREAD

**Issue by dima72** [Alfresco/alfresco-oauth-sample#5]
Dear All,
what  cmisaction for update property with REST would be?

 e.g. I need to update cmis:lastModificationDate of document.

I'm trying to make POST with multipart-data at
https://api.alfresco.com/'+ CompanyName +'/public/cmis/versions/1.0/atom/content?id=' + FileGuid
with parameters like : 

```
        '--' + BOUNDARY +  CRLF +
        'Content-Disposition: form-data; name="propertyValue[0]"' + CRLF +
        'Content-Type: text/plain' + CRLF+CRLF +
        DateTimeToStr( FileTimeToDateTime(timestamp^) )  + CRLF +

        '--' + BOUNDARY +  CRLF +
        'Content-Disposition: form-data; name="propertyId[0]"' + CRLF +
        'Content-Type: text/plain' + CRLF+CRLF +
        'cmis:lastModificationDate' + CRLF +

        '--' + BOUNDARY +  CRLF +
        'Content-Disposition: form-data; name="cmisaction"' + CRLF +
        'Content-Type: text/plain' + CRLF+CRLF +
        'updateProperty' + CRLF +
           '--' + BOUNDARY + '--' + CRLF
```

but I'm getting error from server - Unknown Action!

thanks in advance,

**Comment by jottley** [comment]
The cmis:lastModificationDate should not be updatable by a user.  It is a system set property when the file/node was last modified.

On Jul 27, 2015, at 7:51 AM, Dmitry Konnov <notifications@github.com<mailto:notifications@github.com>> wrote:

Dear All,
what cmisaction for update property with REST would be?

e.g. I need to update cmis:lastModificationDate of document.

I'm trying to make POST with multipart-data at
https://api.alfresco.com/'+ CompanyName +'/public/cmis/versions/1.0/atom/content?id=' + FileGuid
with parameters like :

```
    '--' + BOUNDARY +  CRLF +
    'Content-Disposition: form-data; name="propertyValue[0]"' + CRLF +
    'Content-Type: text/plain' + CRLF+CRLF +
    DateTimeToStr( FileTimeToDateTime(timestamp^) )  + CRLF +

    '--' + BOUNDARY +  CRLF +
    'Content-Disposition: form-data; name="propertyId[0]"' + CRLF +
    'Content-Type: text/plain' + CRLF+CRLF +
    'cmis:lastModificationDate' + CRLF +

    '--' + BOUNDARY +  CRLF +
    'Content-Disposition: form-data; name="cmisaction"' + CRLF +
    'Content-Type: text/plain' + CRLF+CRLF +
    'updateProperty' + CRLF +
       '--' + BOUNDARY + '--' + CRLF
```

but I'm getting error from server - Unknown Action!

thanks in advance,

**Comment by dima72** [comment]
Dear Jared,
please propose a property to store application related data for the document. 
e.g. I need to save ModifiedDate of local file along with uploaded file.

also please show http request to update property for file via REST

Respectfully,

**Comment by jottley** [comment]
In Alfresco Cloud this is accomplished by adding a custom model.  This is a standard feature of onPremise Alfresco but a less talked about feature of Alfresco Cloud.

Here are some things to know about it:

1/ If you are looking at including this as part of Hybrid sync a corresponding model in onPremise Alfresco is required (Hybrid sync is an enterprise only feature)
1a/ The same model cannot be used in both places.  The Cloud version must be name spaced to include the Cloud network name
2/ The properties from your custom model are only visible through the API and not though the myAlfresco UI.

So before I put together any examples what questions or concerns do you have?

On Jul 27, 2015, at 9:10 AM, Dmitry Konnov <notifications@github.com<mailto:notifications@github.com>> wrote:

Dear Jared,
please propose a property to store application related data for the document.
e.g. I need to save ModifiedDate of local file along with uploaded file.

also please show http request to update property for file via REST

Respectfully,

**Comment by dima72** [comment]
In Alfresco Cloud, I want to update
cmis:checkinComment or cmis:description for existing document.

what http request would be for that, sir.

Respectfully,

**Comment by jottley** [comment]
The cmisaction for that would be "update".

**Comment by dima72** [comment]
thank you for suggestion - 'update'

can you please comment on the following, sir:

if i do POST request to
https://api.alfresco.com/'+ CompanyName +'/public/cmis/versions/1.0/atom/?cmisaction=update&content?id=' + FileID + '&cmis:description=testok';

no description is changed.

if i do PUT request to to the above url then file is gone( disappeared from remote side )

if i do POST multipart-data and parameters in form data 

```
    '--' + BOUNDARY +  CRLF +
    'Content-Disposition: form-data; name="propertyValue[0]"' + CRLF +
    'Content-Type: text/plain' + CRLF+CRLF +
    'testok'  + CRLF +
    '--' + BOUNDARY +  CRLF +
    'Content-Disposition: form-data; name="propertyId[0]"' + CRLF +
    'Content-Type: text/plain' + CRLF+CRLF +
    'cmis:description' + CRLF +
    '--' + BOUNDARY +  CRLF +
    'Content-Disposition: form-data; name="cmisaction"' + CRLF +
    'Content-Type: text/plain' + CRLF+CRLF +
    'update' + CRLF +
       '--' + BOUNDARY + '--' + CRLF
```

 then I'm still getting error - Unknown action

Respectfully,

**Comment by jottley** [comment]
The last POST would need to use public/cmis/versions/1.1/browser.  It might work with 1.0 but it would be because of developer preview. 

Doing a POST to https://api.alfresco.com/ottleys.net/public/cmis/versions/1.1/browser/root/sites/jared-ottleys-net/documentlibrary/test.txt 

using 

cmisaction : update
propertyId[0] : cmis:description
propertyValue[0] : testtok
succinct : true

I get back a 200 with the property updated

{"succinctProperties":{"cmis:contentStreamLength":0,"cmis:objectTypeId":"cmis:document","cmis:versionSeriesCheckedOutBy":null,"cmis:versionSeriesCheckedOutId":null,"cmis:isPrivateWorkingCopy":false,"cmis:versionSeriesId":"a99415c8-be5b-4042-90d8-f62477bc18ab","cmis:versionLabel":"1.0","cmis:isLatestVersion":true,"cmis:isVersionSeriesCheckedOut":false,"cmis:lastModifiedBy":"jared@ottleys.net","cmis:createdBy":"jared@ottleys.net","alfcmis:nodeRef":"workspace:\/\/SpacesStore\/a99415c8-be5b-4042-90d8-f62477bc18ab","cmis:isLatestMajorVersion":true,"cmis:contentStreamId":"s3:\/\/ottleys.net\/258ff79c-a781-4a1d-9e5f-2e6b040321ee.bin","cmis:name":"test.txt","cmis:contentStreamMimeType":"text\/plain","cmis:creationDate":1438015684156,"cmis:changeToken":null,"cmis:secondaryObjectTypeIds":["P:sys:localized","P:cm:titled"],"cmis:checkinComment":null,"cmis:objectId":"a99415c8-be5b-4042-90d8-f62477bc18ab;1.0","cmis:isImmutable":false,"cmis:isMajorVersion":true,"cmis:baseTypeId":"cmis:document","cmis:description":"testtok","cmis:lastModificationDate":1438015812417,"cmis:contentStreamFileName":null,"cm:description":"testtok","cm:title":""},"propertiesExtension":{"aspects":{"appliedAspects":["P:sys:localized","P:cm:titled"],"properties":{"propertyString":[{"value":"testtok"},{"value":""}]}}}}

**Comment by dima72** [comment]
Great!
this works. Thank you for support!
